#!/usr/bin/env python

import sys
import json


def main():
    try:
        with open(sys.argv[1], "r+") as f:
            data = json.load(f)
            f.seek(0)
            json.dump(data, f, sort_keys=True, indent=4)
            f.truncate
    except IOError:
        print "File not accessible"
    finally:
        f.close()


if __name__ == '__main__':
    main()
